### ISSUE TITLE
Examples and Tutorials?

### ISSUE THREAD

**Issue by alitavector** [meteorflux/reactive-dependency#6]
Code example will help With greater adoption to your packages.

https://forums.meteor.com/t/patterns-and-practices-for-passing-data-between-templates/2951/85

There were discussions on global session in Meteor and suggested some packages to void security issues. Is your package applicable to their use case? I love to hear the pros and cons too.

**Comment by luisherranz** [comment]
There is an example of this package here:
https://github.com/meteorflux/reactive-dependency-example

I have posted in the thread as well:
https://forums.meteor.com/t/patterns-and-practices-for-passing-data-between-templates/2951/86
